name: Storyville
favicon: null
layout_spectrum: 0.04296
typography_spectrum: 1
title: Storyville - time to read
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#006a7a'
    - '#000000'
    - '#00afce'
    - '#737373'
  brandStrength: 0.4375
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
