name: Storyville
favicon: null
layout_spectrum: 0.9180987109430134
typography_spectrum: 0.20855395263060927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.26250930572859943
  lightness: 0.8773524397984147
  saturation: 0.6900711636990309
  rhythmicContrast: 0.08585346909239888
purpose: []
