typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#020204'
    - '#ee4630'
    - '#8aa6be'
    - '#fbc833'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63991
analytics:
  google: null
  facebook: null
  twitter: null
name: Storyville
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: da
    id: 9a3dd2bf-022e-4245-b394-af20ae874d95
    type: content
favicon: null
title: Storyville - time to read
purpose: []
