name: Storyville
favicon: null
layout_spectrum: 0.63991
typography_spectrum: 1
title: Storyville - time to read
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#27697a'
    - '#000000'
    - '#46adc9'
    - '#818181'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
